# Generated by Django 5.1.1 on 2024-09-19 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_register',
            fields=[
                ('name', models.CharField(max_length=30, null=True)),
                ('email', models.EmailField(max_length=50, primary_key=True, serialize=False)),
                ('mobile', models.CharField(max_length=16, null=True)),
                ('pincode', models.IntegerField(null=True)),
                ('city', models.CharField(max_length=40, null=True)),
                ('address', models.TextField(null=True)),
                ('passwd', models.CharField(max_length=25, null=True)),
                ('picture', models.ImageField(null=True, upload_to='static/profilepicture/')),
                ('red_date', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='tbl_slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(null=True, upload_to='static/slider/')),
                ('title', models.CharField(max_length=40, null=True)),
                ('description', models.TextField(null=True)),
            ],
        ),
    ]
