# Generated by Django 5.1.1 on 2024-09-20 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_tbl_register_tbl_slider'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_provider',
            fields=[
                ('providerName', models.CharField(max_length=100, null=True)),
                ('businessName', models.CharField(max_length=100, null=True)),
                ('providerContact', models.IntegerField(null=True)),
                ('providerEmail', models.EmailField(max_length=100, primary_key=True, serialize=False)),
                ('providerAddress', models.TextField(null=True)),
                ('providerCity', models.CharField(max_length=100, null=True)),
                ('providerPin', models.IntegerField(null=True)),
                ('providerAvgCharge', models.IntegerField(null=True)),
                ('providerDetail', models.TextField(null=True)),
                ('providerServiceImg', models.ImageField(null=True, upload_to='static/service/')),
                ('providerAvlDays', models.IntegerField(null=True)),
                ('providerSvcDate', models.DateField(null=True)),
            ],
        ),
    ]
