# Generated by Django 5.1.1 on 2024-09-21 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_tbl_provider'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_register',
            name='red_date',
        ),
    ]
