# Generated by Django 5.1.1 on 2024-09-23 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_service_provider_delete_tbl_provider'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service_provider',
            old_name='Service_name',
            new_name='service_name',
        ),
    ]
