# Generated by Django 5.1.1 on 2024-09-26 03:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_rename_service_name_service_provider_service_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_title', models.TextField(null=True)),
                ('description', models.TextField(null=True)),
                ('cost', models.IntegerField()),
                ('avg_time', models.TextField(null=True)),
                ('service_pic', models.ImageField(null=True, upload_to='static/servicepic/')),
                ('provider_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.service_provider')),
            ],
        ),
    ]
