# Generated by Django 5.1.1 on 2024-09-26 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_services'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='avg_time',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='services',
            name='service_title',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
