# Generated by Django 5.1.1 on 2024-09-26 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_alter_services_avg_time_alter_services_service_title'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='services',
            new_name='tbl_service',
        ),
    ]
