# Generated by Django 5.1.1 on 2024-09-26 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_tbl_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_booking',
            name='reqdate',
            field=models.DateField(null=True),
        ),
    ]
