# Generated by Django 5.1.1 on 2024-09-26 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_tbl_booking_reqdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_booking',
            name='email',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='tbl_booking',
            name='provider_id',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
