# Generated by Django 5.1.1 on 2024-09-26 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_alter_tbl_booking_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_booking',
            name='status',
            field=models.TextField(max_length=50, null=True),
        ),
    ]
