# Generated by Django 5.1.1 on 2024-09-27 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_tbl_booking_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_booking',
            name='status',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
